name: pull-request
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Run tests 
        run: dotnet test "$GITHUB_WORKSPACE/main/dupe7.test/dupe7.test.csproj"